### ISSUE TITLE
feature request: handle continuations for queries

### ISSUE THREAD

**Issue by fhocutt** [oliver-moran/mediawiki#1]
It would be handy if this library handled query continuations when the number of results requested is greater than the max limit for the request on the API's side. Basically, checking the returned parameter "query-continue", re-running the search starting from that identifier, and appending the results until "query-continue" is empty.

**Comment by oliver-moran** [comment]
fhocutt, thanks and sorry for the delay getting back to you.

I've started a road map page with this suggestion. I'll try and get to it over the next two weeks.

**Comment by oliver-moran** [comment]
fhocutt, I've added support for query continuation to relevant pre-baked functions (when getting a revision history or a category listing).

Query continuation will not be added to the API wrapper functions as these are intended to be handled explicitly by the programmer.
